package JavaScript.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with uuid = 'javascript_02ie' (id = 'JavaScript_02IE')
from your code, and delete the patch script.
*/
deleteBuildType(uuid("javascript_02ie"))

